[0.020s] Invoking command in '/home/david/ros2_ws/build/mycobot_interfaces': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/david/ros2_ws/install/ultraarm:/home/david/ros2_ws/install/mypalletizer_260_pi:/home/david/ros2_ws/install/mypalletizer_260:/home/david/ros2_ws/install/mypalletizer_communication:/home/david/ros2_ws/install/mycobot_630:/home/david/ros2_ws/install/mycobot_600:/home/david/ros2_ws/install/mycobot_320pi:/home/david/ros2_ws/install/mycobot_320:/home/david/ros2_ws/install/mycobot_280pi:/home/david/ros2_ws/install/mycobot_280jn:/home/david/ros2_ws/install/mycobot_280_x3pi:/home/david/ros2_ws/install/mycobot_280:/home/david/ros2_ws/install/myarm_m750:/home/david/ros2_ws/install/myarm_c650:/home/david/ros2_ws/install/myarm_300:/home/david/ros2_ws/install/mycobot_communication:/home/david/ros2_ws/install/mecharm_pi:/home/david/ros2_ws/install/mecharm:/home/david/ros2_ws/install/mecharm_communication:/home/david/ros2_ws/install/mybuddy:/home/david/ros2_ws/install/mycobot_description:/home/david/ros2_ws/install/my_py_pkg:/opt/ros/humble /usr/bin/cmake --build /home/david/ros2_ws/build/mycobot_interfaces -- -j12 -l12
[0.080s] -- Found ament_cmake: 1.3.9 (/opt/ros/humble/share/ament_cmake/cmake)
[0.292s] -- Override CMake install command with custom implementation using symlinks instead of copying resources
[0.308s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.317s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.323s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.375s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.419s] -- Found rclpy: 3.3.13 (/opt/ros/humble/share/rclpy/cmake)
[0.420s] -- Found std_msgs: 4.2.4 (/opt/ros/humble/share/std_msgs/cmake)
[0.874s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.874s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[0.874s]   mycobot_interfaces --arguments-file
[0.874s]   /home/david/ros2_ws/build/mycobot_interfaces/rosidl_adapter__arguments__mycobot_interfaces.json
[0.874s]   --output-dir
[0.874s]   /home/david/ros2_ws/build/mycobot_interfaces/rosidl_adapter/mycobot_interfaces
[0.874s]   --output-file
[0.875s]   /home/david/ros2_ws/build/mycobot_interfaces/rosidl_adapter/mycobot_interfaces.idls)
[0.875s]   returned error code 1:
[0.875s] 
[0.875s]   Error processing 'int16 iD' of 'mycobot_interfaces/MyArucoCoords': ''iD' is
[0.875s]   an invalid field name.  It should have the pattern
[0.875s]   '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$''
[0.875s] 
[0.875s]   Traceback (most recent call last):
[0.875s] 
[0.875s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.875s]       return _run_code(code, main_globals, None,
[0.875s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.876s]       exec(code, run_globals)
[0.876s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.876s]       sys.exit(main())
[0.876s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.876s]       abs_idl_file = convert_to_idl(
[0.876s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[0.876s]       return convert_msg_to_idl(
[0.876s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[0.876s]       msg = parse_message_string(package_name, input_file.stem, content)
[0.877s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 519, in parse_message_string
[0.877s]       fields.append(Field(
[0.877s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 354, in __init__
[0.877s]       raise NameError(
[0.877s] 
[0.877s]   NameError: 'iD' is an invalid field name.  It should have the pattern
[0.877s]   '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$'
[0.877s] 
[0.877s] Call Stack (most recent call first):
[0.878s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.878s]   CMakeLists.txt:43 (rosidl_generate_interfaces)
[0.878s] 
[0.878s] [0m
[0.878s] -- Configuring incomplete, errors occurred!
[0.878s] See also "/home/david/ros2_ws/build/mycobot_interfaces/CMakeFiles/CMakeOutput.log".
[0.881s] gmake: *** [Makefile:3339: cmake_check_build_system] Error 1
[0.884s] Invoked command in '/home/david/ros2_ws/build/mycobot_interfaces' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/david/ros2_ws/install/ultraarm:/home/david/ros2_ws/install/mypalletizer_260_pi:/home/david/ros2_ws/install/mypalletizer_260:/home/david/ros2_ws/install/mypalletizer_communication:/home/david/ros2_ws/install/mycobot_630:/home/david/ros2_ws/install/mycobot_600:/home/david/ros2_ws/install/mycobot_320pi:/home/david/ros2_ws/install/mycobot_320:/home/david/ros2_ws/install/mycobot_280pi:/home/david/ros2_ws/install/mycobot_280jn:/home/david/ros2_ws/install/mycobot_280_x3pi:/home/david/ros2_ws/install/mycobot_280:/home/david/ros2_ws/install/myarm_m750:/home/david/ros2_ws/install/myarm_c650:/home/david/ros2_ws/install/myarm_300:/home/david/ros2_ws/install/mycobot_communication:/home/david/ros2_ws/install/mecharm_pi:/home/david/ros2_ws/install/mecharm:/home/david/ros2_ws/install/mecharm_communication:/home/david/ros2_ws/install/mybuddy:/home/david/ros2_ws/install/mycobot_description:/home/david/ros2_ws/install/my_py_pkg:/opt/ros/humble /usr/bin/cmake --build /home/david/ros2_ws/build/mycobot_interfaces -- -j12 -l12
